apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: poop 
  janus-idp.io/tekton: poop
  backstage.io/kubernetes-id: poop
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: poop
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  