apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: poop-gitops
  description: This is GitOps manifest for poop   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: poop
    janus-idp.io/tekton: poop
    backstage.io/kubernetes-id: poop 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:poop
