apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: poop
  janus-idp.io/tekton: poop
  backstage.io/kubernetes-id: poop
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: poop
resources:
- deployment.yaml
- route.yaml
- service.yaml
