apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: poop
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: poop 
  name: poop
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: poop
    weight: 100 
