apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: poop
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: poop 
  name: poop
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: poop 
